version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: unsplash-js
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.6
    - 7.0.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: pug
    versions:
    - 3.0.0
  - dependency-name: parcel-bundler
    versions:
    - 1.12.4
